library(devtools)
doll <- foreign::read.spss(file='./data-raw/doll.sav', to.data.frame=TRUE)
usethis::use_data(doll, overwrite = TRUE)
bmt <- foreign::read.spss(file='./data-raw/bmt.sav', to.data.frame=TRUE)
usethis::use_data(bmt, overwrite = TRUE)
ova <- foreign::read.spss(file='./data-raw/ova.sav', to.data.frame=TRUE)
usethis::use_data(ova, overwrite = TRUE)
fracture <- foreign::read.spss(file='./data-raw/fracture.sav', to.data.frame=TRUE)
usethis::use_data(fracture, overwrite = TRUE)
LBW <- foreign::read.spss(file='./data-raw/LBW.sav', to.data.frame=TRUE)
usethis::use_data(LBW, overwrite = TRUE)
endom <- foreign::read.spss(file='./data-raw/endom.sav', to.data.frame=TRUE)
usethis::use_data(endom, overwrite = TRUE)
teeth <- read.table('./data-raw/teeth.dat', header = TRUE)
usethis::use_data(teeth, overwrite = TRUE)
epilepsy <- read.table('./data-raw/epilepsy.dat', header = TRUE)
usethis::use_data(epilepsy, overwrite = TRUE)
melanoma <- read.table('./data-raw/melanoma.dat', header = TRUE)
usethis::use_data(melanoma, overwrite = TRUE)
